{"trial_id": "0", "hyperparameters": {"space": [], "values": {}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/saparia/anaconda3/lib/python3.7/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/saparia/anaconda3/lib/python3.7/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/saparia/anaconda3/lib/python3.7/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/home/saparia/anaconda3/lib/python3.7/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/home/saparia/anaconda3/lib/python3.7/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/home/saparia/anaconda3/lib/python3.7/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/saparia/anaconda3/lib/python3.7/site-packages/keras/engine/training.py\", line 3691, in _assert_compile_was_called\n    \"You must compile your model before \"\nRuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.\n"}